name: Release Package

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          cache: pnpm

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .turbo/cache
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install Dependencies
        run: pnpm i

      - name: Create Release PR or Publish Packages
        id: changesets
        uses: changesets/action@v1
        with:
          # Builds the package and executes `changeset publish`
          publish: pnpm release
          # Alias to `changeset version` script in package.json
          version: pnpm versioning
          commit: 'chore: update package versions'
          title: 'Publish NPM Package'
          createGithubReleases: 'true'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
